app/mod_user/user/models.py
from dateabase_models.user import User, NotUserAuthenticated

app/mod_user/user/forms.py
import re

from flask_wtf import FlaskForm
from wtforms.fields import (StringField, PasswordField, BooleanField)
from wtforms.validators import (DataRequired, Email, EqualTo,
                                 Length, ValidationError)

from wtforms.widgets import PasswordInput
from utlis.forms import _get_fields

from app import bcrypt
from .models import User



class LoginForm(FlaskForm):
    email = StringField('Enter Your Email : ',
                        validators=(DataRequired(), Email()), description='email@gmail.com')
    
    password = PasswordField('Enter Your Password : ',
                             validators=(DataRequired(),), description='*'*8)
    remember = BooleanField('Remember', default=False)
    def validate_email(self, email):
        user = User.query.filter(User.email.ilike(f'{email.data}')).first()
        if (not user) or (not bcrypt.check_password_hash(user.password , self.password.data)) :
            raise ValidationError('The email or password is incorrect')
    
    def get_fields(self):
        return _get_fields(self)
# End

class RegisterForm(FlaskForm):
    full_name = StringField('Enter Your Full Name : ',
                            validators=(DataRequired(),), description='Full Name')
    email = StringField('Enter Your Email : ',
                        validators=(DataRequired(), Email()), description='email@gmail.com')
    password = PasswordField('Enter Your Password : ',
                             validators=(DataRequired(), Length(8,128)), description='*'*8)
    confirm_password = PasswordField(
        name='Confirm Your Password :',
        validators=(DataRequired(),
                    Length(8,128), EqualTo('password')), description='*'*8)
    
    def validate_email_(email):
        _ = User.query.filter(
                User.email.ilike(f'{email.date}'))
        if _:
            raise ValidationError('This Email Already Exists')
    
    def get_fields(self):
        return _get_fields(self)
# End

class SettingForm(FlaskForm):
    full_name = StringField('Your Full Name : ',
                        validators=(DataRequired(),), description='Full Name')
    email = StringField('Your Email : ',
                        validators=(DataRequired(), Email()), description='email@gmail.com')
    
    old_password = StringField('Enter Your Old Password : ',
                            validators=(DataRequired(), Length(8,128)),
                            widget=PasswordInput(hide_value=False))
    
    password = StringField('Enter Your New Password : ',
                            validators=(DataRequired(), Length(8,128)),
                            widget=PasswordInput(hide_value=False))
    
    confirm_password = StringField( name='Confirm Your New Password :',
                        validators=(DataRequired(), Length(8,128), EqualTo('password')),
                        widget=PasswordInput(hide_value=False))
# End    
    

app/mod_user/user/__init__.py
from flask import Blueprint

from app import app

user = Blueprint('user', __name__,
                  url_prefix='/profile/')

from .models import *
from .routes import *

app/mod_user/user/routes.py
# Flask libs
from flask import (flash, url_for, redirect,
                    render_template, abort, request)
from flask_login import login_user, logout_user, current_user
from sqlalchemy.exc import IntegrityError
# ---

# Local libs
from . import user
from .models import User, NotUserAuthenticated
from .forms import LoginForm, RegisterForm, SettingForm
from .utlis import add_to_redis, get_from_redis, delete_from_redis, send_registration_message

from app import db, bcrypt, Configs

from utlis.flask_login import not_logged_in, login_required
from mod_application.memory_management.group import GroupManager
from mod_application.memory_management.task import TasksManager
from mod_application.memory_management.event import EventManager

from dateabase_models._models import Event, Task
# ---

@user.route('/', methods=['GET'])
@login_required('user.profile')
def profile():
    user:User = current_user
    
    # Has the user confirmed her email?
    user_not_auth = NotUserAuthenticated.query.filter(
            NotUserAuthenticated.user_id.like(user.id)).first()

    if user_not_auth:
        return redirect(url_for('user.confirm_registration'))

    task_total, task_done_total = user.total_task, user.total_task_done
    event_total, event_done_total = user.total_event, user.total_event

    return render_template(
        'user/profile.html', title='Profile', 
        task_total=task_total, task_done_total=task_done_total,
        event_total=event_total, event_done_total=event_total)
# End Function

@user.route('login/', methods=['GET', 'POST'])
@not_logged_in('user.profile')
def login():
    form = LoginForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash('Email or password is not valid!!!')
            return render_template('user/forms-A.html', title='Login', form=form)
        # ---

        user = User.query.filter(User.email.ilike(f'{form.email.data}')).first()
        if not user: # Not Found User
            flash("Something went wrong. Please try again")
            return render_template('user/forms-A.html', title='Login', form=form)
        # ---

        login_user(user, remember=form.remember.data)

        # Has the user confirmed her email?
        user_not_auth = NotUserAuthenticated.query.filter(
                NotUserAuthenticated.user_id.like(user.id)).first()

        if user_not_auth:
            return redirect(url_for('user.confirm_registration'))
        # ---
        
        flash('You have successfully logged in' , 'info')
        
        __next = request.args.get('next', type=str,
                                  default=url_for('user.profile'))
        return redirect(__next)
    # ---
    return render_template('user/forms-A.html',
                title='Login', form=form)
# End Function

@user.route('register/', methods=['GET', 'POST'])
@not_logged_in('user.profile')
def register():
    form = RegisterForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash('The information is invalid')
            return render_template('user/forms-A.html', title='Register', form=form)
        # ---

        # Remaining: Email confirmation must be added
        NewUser = User(
            full_name=form.full_name.data,
            email=form.email.data,
            password=bcrypt.generate_password_hash(
                            password=form.password.data))
        # ---

        NewUser.groups = GroupManager().return_group_in_pickle
        
        # Create Roll Task And Event 
        NewTask = Task(
            TasksManager().return_tasks_in_pickle)
        NewEvent = Event(
            TasksManager().return_tasks_in_pickle)
        # ---

        # Create Relation 
        NewTask.user = NewUser
        NewEvent.user = NewUser
        # ---
        try:
            db.session.add_all([NewEvent, NewTask, NewUser])
            db.session.commit()
            
            # Add new user to unauthenticated users
            db.session.add(NotUserAuthenticated(NewUser.id))
            db.session.commit()
            # ---
        except IntegrityError:
            db.session.rollback()
            flash('Error! Try again (probably because the email you entered already exists)')
            return render_template('user/forms-A.html', title='Register', form=form)

        else:
            flash('Your account has been created successfully')
            return redirect(url_for('user.login'))

    return render_template('user/forms-A.html', 
                    title='Register', form=form)
# End Function

@user.route('logout/', methods=['GET'])
@login_required()
def logout():
    logout_user()
    flash('Logout was successful.')
    return redirect('/')
# End Function

@user.route('settings/', methods=['GET', 'POST'])
@login_required(_next_endpoint='user.settings')
def settings():
    form  = SettingForm()
    user:User = current_user

    if request.method == 'GET':
        form.email.data = user.email
        form.full_name.data = user.full_name
        
        form.old_password.data, form.password.data,\
            form.confirm_password.data  = '*'*8, '*'*8, '*'*8
        
    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template('user/settings.html', title='Setting Account',
                        form=form, submit_button='Update')
        
        user.full_name = form.full_name.data

        # Checks that in the password fields ([not 8 stars] : '*'*8 )
        _password_not_asterisk = '*'*8 in [form.confirm_password.data, 
                                           form.old_password.data, form.password.data]
        
        # Checks that the user has entered the account password correctly
        _password_must_be_correct = bcrypt.check_password_hash(
                                    user.password, form.old_password.data)\
                                    if not _password_not_asterisk else False
        
        if _password_must_be_correct :
            user.password = bcrypt.generate_password_hash(form.password.data)
        # ---

        if form.email.data != user.email:
            # Remaining: Email confirmation must be added
            user.email = form.email.data
            # Add new user to unauthenticated users
            db.session.add(NotUserAuthenticated(user.id))
        # ---

        try:
            db.session.commit()
        except IntegrityError:
            flash('Updating your profile information failed! Please try again.')
            db.session.rollback()
        else:
            flash('Your profile information has been successfully updated .')
            
            if _password_must_be_correct:
                flash('Your password has been successfully updated .')

    return render_template('user/settings.html', title='Setting Account',
                           form=form, submit_button='Update')
# End Function

@user.route('/delete', methods=['GET'])
@login_required('user.profile')
def delete():
    user:User = User.query.get(current_user.id)
    
    for event in user.events : db.session.delete(event)
    for task in user.tasks : db.session.delete(task)

    db.session.delete(user)
    db.session.commit()

    return redirect(url_for('user.login'))
# End Function


@user.route('/confirm/')
@login_required('user.confirm_registration')
def confirm_registration():
    
    # Get Datas
    email = current_user.email
    resend = request.args.get(key='resend')
    token = request.args.get(key='token', type=str)

    # To resend the email
    if resend :
        # for beauty and not sending flash messages
        if token:
            return redirect(
                url_for('user.confirm_registration', token=token))
        # ---
        flash('The authentication email has been re-sent to your email address')
    # ---

    # Request without arguments
    if (not token):
        """
        If you send a request to this room without a token argument 
        (an authentication token will be created and sent)
        """
        token = add_to_redis(current_user, 'register')
        send_registration_message(current_user, token)
        
        return render_template('user/email-confirmation-required.html',
        msg=f"""Account activation link sent to your email address: 
                {Configs.MAIL_USERNAME} 
                Please follow the link inside to continue.""")
    # ---

    user_auth = NotUserAuthenticated.query.filter(
        NotUserAuthenticated.user_id.like(current_user.id)).first()

    # If the user is active    
    if not user_auth:
        return render_template(
            'user/email-confirmation-required.html',
            msg=f"This user is already activated. <br> <a href='{url_for('user.profile')}'>Profile</a>")
    # ---

    # Checking the validity of the token
    token_from_redis = get_from_redis(current_user, 'register')
    
    if (not token_from_redis) or \
        (str(token) != token_from_redis.decode('UTF-8')):
        return render_template(
            'user/email-confirmation-required.html',
            msg=f"The token has expired!")
    # ---

    # Activate the user
    delete_from_redis(current_user, 'register')
    db.session.delete(user_auth)
    db.session.commit()
    # ---

    flash('Your email has been successfully verified! welcome')
    return redirect(url_for('user.profile'))
# End Function
    

app/templates/user/base.html
{% extends "base.html" %}

{% block menu %}
  {% include 'user/_inc/menu.html'   %}
{% endblock menu %}

app/templates/user/forms-A.html
{% extends 'user/base.html' %}

{% block menu %}
{% include 'user/_inc/menu-[login-register].html' %}
{% endblock %}

{% block content %}
    {% include 'user/_inc/dynamic_form.html'   %}
{% endblock %}

app/templates/user/profile.html
{% extends "user/base.html" %}

{% block content %}

<div class="row">
  <div class="col-lg-8 mb-4 order-0">
    <div class="card">
      <div class="d-flex align-items-end row">
        <div class="col-sm-7">
          <div class="card-body">
            <h5 class="card-title text-primary" style="text-transform: capitalize;">hello {{ current_user.full_name }}! 🎉</h5>
            <p class="mb-4">
              Most people don't plan to fail, they just don't plan 
            </p>
          </div>
        </div>
        <div class="col-sm-5 text-center text-sm-left">
          <div class="card-body pb-0 px-0 px-md-4">
            <img src="/static/assets/img/illustrations/man-with-laptop-light.png" height="140" alt="View Badge User"
              data-app-dark-img="illustrations/man-with-laptop-dark.png"
              data-app-light-img="illustrations/man-with-laptop-light.png">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-4 order-1">
    <div class="row">
      <div class="col-lg-6 col-md-12 col-6 mb-4">
        <div class="card">
          <div class="card-body">
            <div class="card-title d-flex align-items-start justify-content-between">
              <div class="avatar flex-shrink-0">
                <i class='bx bx-spreadsheet' id="icon-task"></i>
              </div>
              <div class="dropdown">
                <button class="btn p-0" type="button" id="cardOpt3" data-bs-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                  <i class="bx bx-dots-vertical-rounded"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
                  <a class="dropdown-item" href="javascript:void(0);">View More</a>
                </div>
              </div>
            </div>
            <span class="fw-medium d-block mb-1">Task's</span>
            <h3 class="card-title mb-2">{{ task_total }}</h3>
            <small class="text-success fw-medium"><i class="bx bx-task"></i> {{ task_done_total }}</small>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 col-6 mb-4">
        <div class="card">
          <div class="card-body" style="padding-bottom: 32px;">
            <div class="card-title d-flex align-items-start justify-content-between">
              <div class="avatar flex-shrink-0">
                <i class='bx bx-calendar-event' id="icon-event"></i>
              </div>
              <div class="dropdown">
                <button class="btn p-0" type="button" id="cardOpt6" data-bs-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                  <i class="bx bx-dots-vertical-rounded"></i>
                </button>

              </div>
            </div>
            <span>Event's</span>
            <h3 class="card-title text-nowrap mb-1">{{event_total}}</h3>
            <small class="text-success fw-medium">
              <i class="bx bx-task"></i>{{event_done_total}}
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Task and event diagram -->
  <div class="col-12 col-lg-8 order-2 order-md-3 order-lg-2 mb-4">
    <div class="card">
      <div class="row row-bordered g-0">
        <div class="col-md-8">
          <center>This section will be completed soon ... </center>
          <br><br>
          <h5 class="card-header m-0 me-2 pb-3" style="text-transform: capitalize;">Task and event diagram</h5>
          <div id="totalRevenueChart" class="px-2"></div>
        </div>
        <div class="col-md-4">
          <div class="card-body">
            <div class="text-center">
              <div class="dropdown">

              </div>
            </div>
          </div>
          <div id="growthChart"></div>
          <div class="text-center fw-medium pt-3 mb-2">00.00% Scheduled Time</div>


        </div>
      </div>
    </div>
  </div>




  <div class="col-12 col-md-8 col-lg-4 order-3 order-md-2">
    <div class="card h-100">

      <div class="card-header d-flex align-items-center justify-content-between pb-0">
        <div class="card-title mb-0">
          <center>This section will be completed soon ... </center>
          <br>
          <h5 class="m-0 me-2">How did you spend the time ?</h5>
          <small class="text-muted">00.00</small>
        </div>
        <div class="dropdown">
          <button class="btn p-0" type="button" id="orederStatistics" data-bs-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <i class="bx bx-dots-vertical-rounded"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="orederStatistics">
            <a class="dropdown-item" href="">Refresh</a>

          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <div class="d-flex flex-column align-items-center gap-1">
            <h2 class="mb-2">00.00</h2>
            <span>----</span>
          </div>
          <div id="orderStatisticsChart"></div>
        </div>

      </div>
    </div>
  </div>
</div>


{% endblock %}

app/templates/user/settings.html
{% extends 'user/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-pills flex-column flex-md-row mb-3">
      <li class="nav-item">
        <a class="nav-link active"><i class="bx bx-user me-1"></i> Account</a>
      </li>
    </ul>
    <div class="card mb-4">
      <h5 class="card-header">Profile Details</h5>
      <!-- Account -->
      <div class="card-body">
        <div class="d-flex align-items-start align-items-sm-center gap-4">
          <img src="/static/assets/img/avatars/1.png" alt="user-avatar" class="d-block rounded" height="100" width="100"
            id="uploadedAvatar">
          <div class="button-wrapper">
            <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
              <span class="d-none d-sm-block">Upload new photo</span>
              <i class="bx bx-upload d-block d-sm-none"></i>
              <input disabled type="file" id="upload"
               class="account-file-input" hidden="" accept="image/png, image/jpeg">
            </label>
            <button disabled type="button" class="btn btn-outline-secondary account-image-reset mb-4">
              <i class="bx bx-reset d-block d-sm-none"></i>
              <span class="d-none d-sm-block">Reset</span>
            </button>

            <p class="text-muted mb-0">Allowed JPG, GIF or PNG. Max size of 800K</p>
          </div>
        </div>
      </div>
      <hr class="my-0">
      <div class="card-body">
        <form id="formAuthentication" class="mb-3" action="{{ request.full_path }}" method="POST">
          {{ form.hidden_tag() }} {% for field in form if not field.widget.input_type == 'hidden' %} {% if
          field.widget.input_type == 'checkbox' %}
          <div class="form-group form-check">
            {{field.label(class="form-check-label")}} {{field(class="form-check-input")}}
          </div>
          <br> {% endif %} {% if field.widget.input_type in ['text', 'password'] %}
          <div class="form-group">
            {{field.label(class="col-md-12")}}
            <div class="col-md-12">
              {{ field(class="form-control form-control-line", placeholder=field.description) }}
            </div>
          </div>
          <br> {% endif %} {% endfor %}
          <br>
          <div class="form-group">
            <div class="col-sm-12">
              <button class="btn btn-primary d-grid w-100" type="submit">
                {{ submit_button or title }}
              </button>
            </div>
          </div>
        </form>
      </div>
      <!-- /Account -->
    </div>
    <div class="card">
      <h5 class="card-header">Delete Account</h5>
      <div class="card-body">
        <div class="mb-3 col-12 mb-0">
          <div class="alert alert-warning">
            <h6 class="alert-heading mb-1">Are you sure you want to delete your account?</h6>
            <p class="mb-0">Once you delete your account, there is no going back. Please be certain.</p>
          </div>
        </div>

          <a href="{{url_for('user.delete')}}" class="btn btn-danger deactivate-account">Deactivate Account</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}