app/mod_user/user/models.py
from dateabase_models.user import User, NotUserAuthenticated

app/mod_user/user/forms.py
import re

from flask_wtf import FlaskForm
from wtforms.fields import (StringField, PasswordField, BooleanField)
from wtforms.validators import (DataRequired, Email, EqualTo,
                                 Length, ValidationError)

from wtforms.widgets import PasswordInput
from utlis.forms import _get_fields

from app import bcrypt
from .models import User



class LoginForm(FlaskForm):
    email = StringField('Enter Your Email : ',
                        validators=(DataRequired(), Email()), description='email@gmail.com')
    
    password = PasswordField('Enter Your Password : ',
                             validators=(DataRequired(),), description='*'*8)
    remember = BooleanField('Remember', default=False)
    def validate_email(self, email):
        user = User.query.filter(User.email.ilike(f'{email.data}')).first()
        if (not user) or (not bcrypt.check_password_hash(user.password , self.password.data)) :
            raise ValidationError('The email or password is incorrect')
    
    def get_fields(self):
        return _get_fields(self)
# End

class RegisterForm(FlaskForm):
    full_name = StringField('Enter Your Full Name : ',
                            validators=(DataRequired(),), description='Full Name')
    email = StringField('Enter Your Email : ',
                        validators=(DataRequired(), Email()), description='email@gmail.com')
    password = PasswordField('Enter Your Password : ',
                             validators=(DataRequired(), Length(8,128)), description='*'*8)
    confirm_password = PasswordField(
        name='Confirm Your Password :',
        validators=(DataRequired(),
                    Length(8,128), EqualTo('password')), description='*'*8)
    
    def validate_email_(email):
        _ = User.query.filter(
                User.email.ilike(f'{email.date}'))
        if _:
            raise ValidationError('This Email Already Exists')
    
    def get_fields(self):
        return _get_fields(self)
# End

class SettingForm(FlaskForm):
    full_name = StringField('Your Full Name : ',
                        validators=(DataRequired(),), description='Full Name')
    email = StringField('Your Email : ',
                        validators=(DataRequired(), Email()), description='email@gmail.com')
    
    old_password = StringField('Enter Your Old Password : ',
                            validators=(DataRequired(), Length(8,128)),
                            widget=PasswordInput(hide_value=False))
    
    password = StringField('Enter Your New Password : ',
                            validators=(DataRequired(), Length(8,128)),
                            widget=PasswordInput(hide_value=False))
    
    confirm_password = StringField( name='Confirm Your New Password :',
                        validators=(DataRequired(), Length(8,128), EqualTo('password')),
                        widget=PasswordInput(hide_value=False))
# End    
    

app/mod_user/user/__init__.py
from flask import Blueprint

from app import app

user = Blueprint('user', __name__,
                  url_prefix='/profile/')

from .models import *
from .routes import *

app/mod_user/user/routes.py
# Flask libs
from flask import (flash, url_for, redirect,
                    render_template, abort, request)
from flask_login import login_user, logout_user, current_user
from sqlalchemy.exc import IntegrityError
# ---

# Local libs
from . import user
from .models import User, NotUserAuthenticated
from .forms import LoginForm, RegisterForm, SettingForm
from .utlis import add_to_redis, get_from_redis, delete_from_redis, send_registration_message

from app import db, bcrypt, Configs

from utlis.flask_login import not_logged_in, login_required
from mod_application.memory_management.group import GroupManager
from mod_application.memory_management.task import TasksManager
from mod_application.memory_management.event import EventManager

from dateabase_models._models import Event, Task
# ---

@user.route('/', methods=['GET'])
@login_required('user.profile')
def profile():
    user:User = current_user
    
    # Has the user confirmed her email?
    user_not_auth = NotUserAuthenticated.query.filter(
            NotUserAuthenticated.user_id.like(user.id)).first()

    if user_not_auth:
        return redirect(url_for('user.confirm_registration'))

    task_total, task_done_total = user.total_task, user.total_task_done
    event_total, event_done_total = user.total_event, user.total_event

    return render_template(
        'user/profile.html', title='Profile', 
        task_total=task_total, task_done_total=task_done_total,
        event_total=event_total, event_done_total=event_total)
# End Function

@user.route('login/', methods=['GET', 'POST'])
@not_logged_in('user.profile')
def login():
    form = LoginForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash('Email or password is not valid!!!')
            return render_template('user/forms-A.html', title='Login', form=form)
        # ---

        user = User.query.filter(User.email.ilike(f'{form.email.data}')).first()
        if not user: # Not Found User
            flash("Something went wrong. Please try again")
            return render_template('user/forms-A.html', title='Login', form=form)
        # ---

        login_user(user, remember=form.remember.data)

        # Has the user confirmed her email?
        user_not_auth = NotUserAuthenticated.query.filter(
                NotUserAuthenticated.user_id.like(user.id)).first()

        if user_not_auth:
            return redirect(url_for('user.confirm_registration'))
        # ---
        
        flash('You have successfully logged in' , 'info')
        
        __next = request.args.get('next', type=str,
                                  default=url_for('user.profile'))
        return redirect(__next)
    # ---
    return render_template('user/forms-A.html',
                title='Login', form=form)
# End Function

@user.route('register/', methods=['GET', 'POST'])
@not_logged_in('user.profile')
def register():
    form = RegisterForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash('The information is invalid')
            return render_template('user/forms-A.html', title='Register', form=form)
        # ---

        # Remaining: Email confirmation must be added
        NewUser = User(
            full_name=form.full_name.data,
            email=form.email.data,
            password=bcrypt.generate_password_hash(
                            password=form.password.data))
        # ---

        NewUser.groups = GroupManager().return_group_in_pickle
        
        # Create Roll Task And Event 
        NewTask = Task(
            TasksManager().return_tasks_in_pickle)
        NewEvent = Event(
            TasksManager().return_tasks_in_pickle)
        # ---

        # Create Relation 
        NewTask.user = NewUser
        NewEvent.user = NewUser
        # ---
        try:
            db.session.add_all([NewEvent, NewTask, NewUser])
            db.session.commit()
            
            # Add new user to unauthenticated users
            db.session.add(NotUserAuthenticated(NewUser.id))
            db.session.commit()
            # ---
        except IntegrityError:
            db.session.rollback()
            flash('Error! Try again (probably because the email you entered already exists)')
            return render_template('user/forms-A.html', title='Register', form=form)

        else:
            flash('Your account has been created successfully')
            return redirect(url_for('user.login'))

    return render_template('user/forms-A.html', 
                    title='Register', form=form)
# End Function

@user.route('logout/', methods=['GET'])
@login_required()
def logout():
    logout_user()
    flash('Logout was successful.')
    return redirect('/')
# End Function

@user.route('settings/', methods=['GET', 'POST'])
@login_required(_next_endpoint='user.settings')
def settings():
    form  = SettingForm()
    user:User = current_user

    if request.method == 'GET':
        form.email.data = user.email
        form.full_name.data = user.full_name
        
        form.old_password.data, form.password.data,\
            form.confirm_password.data  = '*'*8, '*'*8, '*'*8
        
    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template('user/settings.html', title='Setting Account',
                        form=form, submit_button='Update')
        
        user.full_name = form.full_name.data

        # Checks that in the password fields ([not 8 stars] : '*'*8 )
        _password_not_asterisk = '*'*8 in [form.confirm_password.data, 
                                           form.old_password.data, form.password.data]
        
        # Checks that the user has entered the account password correctly
        _password_must_be_correct = bcrypt.check_password_hash(
                                    user.password, form.old_password.data)\
                                    if not _password_not_asterisk else False
        
        if _password_must_be_correct :
            user.password = bcrypt.generate_password_hash(form.password.data)
        # ---

        if form.email.data != user.email:
            # Remaining: Email confirmation must be added
            user.email = form.email.data
            # Add new user to unauthenticated users
            db.session.add(NotUserAuthenticated(user.id))
        # ---

        try:
            db.session.commit()
        except IntegrityError:
            flash('Updating your profile information failed! Please try again.')
            db.session.rollback()
        else:
            flash('Your profile information has been successfully updated .')
            
            if _password_must_be_correct:
                flash('Your password has been successfully updated .')

    return render_template('user/settings.html', title='Setting Account',
                           form=form, submit_button='Update')
# End Function

@user.route('/delete', methods=['GET'])
@login_required('user.profile')
def delete():
    user:User = User.query.get(current_user.id)
    
    for event in user.events : db.session.delete(event)
    for task in user.tasks : db.session.delete(task)

    db.session.delete(user)
    db.session.commit()

    return redirect(url_for('user.login'))
# End Function


@user.route('/confirm/')
@login_required('user.confirm_registration')
def confirm_registration():
    
    # Get Datas
    email = current_user.email
    resend = request.args.get(key='resend')
    token = request.args.get(key='token', type=str)

    # To resend the email
    if resend :
        # for beauty and not sending flash messages
        if token:
            return redirect(
                url_for('user.confirm_registration', token=token))
        # ---
        flash('The authentication email has been re-sent to your email address')
    # ---

    # Request without arguments
    if (not token):
        """
        If you send a request to this room without a token argument 
        (an authentication token will be created and sent)
        """
        token = add_to_redis(current_user, 'register')
        send_registration_message(current_user, token)
        
        return render_template('user/email-confirmation-required.html',
        msg=f"""Account activation link sent to your email address: 
                {Configs.MAIL_USERNAME} 
                Please follow the link inside to continue.""")
    # ---

    user_auth = NotUserAuthenticated.query.filter(
        NotUserAuthenticated.user_id.like(current_user.id)).first()

    # If the user is active    
    if not user_auth:
        return render_template(
            'user/email-confirmation-required.html',
            msg=f"This user is already activated. <br> <a href='{url_for('user.profile')}'>Profile</a>")
    # ---

    # Checking the validity of the token
    token_from_redis = get_from_redis(current_user, 'register')
    
    if (not token_from_redis) or \
        (str(token) != token_from_redis.decode('UTF-8')):
        return render_template(
            'user/email-confirmation-required.html',
            msg=f"The token has expired!")
    # ---

    # Activate the user
    delete_from_redis(current_user, 'register')
    db.session.delete(user_auth)
    db.session.commit()
    # ---

    flash('Your email has been successfully verified! welcome')
    return redirect(url_for('user.profile'))
# End Function
    

app/templates/user/_inc/dynamic_form.html
<div class="authentication-wrapper authentication-basic container-p-y" style="margin: 0 20px;">
  <div class="authentication-inner">
    <!-- Register -->
    <div class="card">
      <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
          <a href="index.html" class="app-brand-link gap-2">
            <span class="app-brand-logo demo">
              <svg width="25" viewBox="0 0 25 42" version="1.1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink">
                <defs>
                  <path
                    d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                    id="path-1"></path>
                  <path
                    d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                    id="path-3"></path>
                  <path
                    d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                    id="path-4"></path>
                  <path
                    d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                    id="path-5"></path>
                </defs>
                <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                    <g id="Icon" transform="translate(27.000000, 15.000000)">
                      <g id="Mask" transform="translate(0.000000, 8.000000)">
                        <mask id="mask-2" fill="white">
                          <use xlink:href="#path-1"></use>
                        </mask>
                        <use fill="#696cff" xlink:href="#path-1"></use>
                        <g id="Path-3" mask="url(#mask-2)">
                          <use fill="#696cff" xlink:href="#path-3"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                        </g>
                        <g id="Path-4" mask="url(#mask-2)">
                          <use fill="#696cff" xlink:href="#path-4"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                        </g>
                      </g>
                      <g id="Triangle"
                        transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                        <use fill="#696cff" xlink:href="#path-5"></use>
                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </span>
            <span class="app-brand-text demo text-body fw-bold">Calander</span>
          </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2"></h4>

        <form id="formAuthentication" class="mb-3"
          action="{{ request.full_path }}" method="POST">
          {{ form.hidden_tag() }}

          {% for field in form if not field.widget.input_type == 'hidden' %}

          {% if field.widget.input_type == 'checkbox' %}
          <div class="form-group form-check">
            {{field.label(class="form-check-label")}}
            {{field(class="form-check-input")}}
          </div>
          <br>
          {% endif %}

          {% if field.widget.input_type in ['text', 'password'] %}
          <div class="form-group">
            {{field.label(class="col-md-12")}}
            <div class="col-md-12">
              {{ field(class="form-control form-control-line", placeholder=field.description) }}
            </div>
          </div>
          <br>
          {% endif %}



          {% endfor %}
          <br>
          <div class="form-group">
            <div class="col-sm-12">
              <button class="btn btn-primary d-grid w-100" type="submit">
                {{ submit_button or title }}
              </button>
            </div>
          </div>
        </form>
      </div>
      </div>
    </div>
  </div>

app/templates/user/_inc/footer.html
<footer class="footer text-center">
    All Rights Reserved by Xtreme Admin. Designed and Developed by
    <a href="https://www.wrappixel.com">WrapPixel</a>.
  </footer>

app/templates/user/_inc/header.html
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
      <div class="navbar-header" data-logobg="skin5">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <a class="navbar-brand" href="index.html">
          <!-- Logo icon -->
          <b class="logo-icon">
            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
            <!-- Dark Logo icon -->
            <img
              src="../assets/images/logo-icon.png"
              alt="homepage"
              class="dark-logo"
            />
            <!-- Light Logo icon -->
            <img
              src="../assets/images/logo-light-icon.png"
              alt="homepage"
              class="light-logo"
            />
          </b>
          <!--End Logo icon -->
          <!-- Logo text -->
          <span class="logo-text">
            <!-- dark Logo text -->
            <img
              src="../assets/images/logo-text.png"
              alt="homepage"
              class="dark-logo"
            />
            <!-- Light Logo text -->
            <img
              src="../assets/images/logo-light-text.png"
              class="light-logo"
              alt="homepage"
            />
          </span>
        </a>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <!-- This is for the sidebar toggle which is visible on mobile only -->
        <a
          class="nav-toggler waves-effect waves-light d-block d-md-none"
          href="javascript:void(0)"
          ><i class="ti-menu ti-close"></i
        ></a>
      </div>
      <!-- ============================================================== -->
      <!-- End Logo -->
      <!-- ============================================================== -->
      <div
        class="navbar-collapse collapse"
        id="navbarSupportedContent"
        data-navbarbg="skin5"
      >
        <!-- ============================================================== -->
        <!-- toggle and nav items -->
        <!-- ============================================================== -->
        <ul class="navbar-nav float-start me-auto">
          <!-- ============================================================== -->
          <!-- Search -->
          <!-- ============================================================== -->
          <li class="nav-item search-box">
            <a
              class="nav-link waves-effect waves-dark"
              href="javascript:void(0)"
              ><i class="mdi mdi-magnify fs-4"></i
            ></a>
            <form class="app-search position-absolute">
              <input
                type="text"
                class="form-control"
                placeholder="Search &amp; enter"
              />
              <a class="srh-btn"><i class="mdi mdi-close"></i></a>
            </form>
          </li>
        </ul>
        <!-- ============================================================== -->
        <!-- Right side toggle and nav items -->
        <!-- ============================================================== -->
        <ul class="navbar-nav float-end">
          <!-- ============================================================== -->
          <!-- User profile and search -->
          <!-- ============================================================== -->
          <li class="nav-item dropdown">
            <a
              class="
                nav-link
                dropdown-toggle
                text-muted
                waves-effect waves-dark
                pro-pic
              "
              href="#"
              id="navbarDropdown"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="../assets/images/users/1.jpg"
                alt="user"
                class="rounded-circle"
                width="31"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end user-dd animated"
              aria-labelledby="navbarDropdown"
            >
              <a class="dropdown-item" href="javascript:void(0)"
                ><i class="mdi mdi-account m-r-5 m-l-5"></i> My Profile</a
              >
              <a class="dropdown-item" href="javascript:void(0)"
                ><i class="mdi mdi-wallet m-r-5 m-l-5"></i> My Balance</a
              >
              <a class="dropdown-item" href="javascript:void(0)"
                ><i class="mdi mdi-email m-r-5 m-l-5"></i> Inbox</a
              >
            </ul>
          </li>
          <!-- ============================================================== -->
          <!-- User profile and search -->
          <!-- ============================================================== -->
        </ul>
      </div>
    </nav>
  </header>

app/templates/user/_inc/menu-[login-register].html
<ul class="menu-inner py-1 ps ps--active-y">
    <li class="menu-item">
        <a href="{{ url_for('user.login') }}"  class="menu-link">
            <i class="menu-icon tf-icons bx bx-user"></i>
            <div data-i18n="Login">Login</div>
        </a>
    </li>

    <li class="menu-item">
        <a href="{{ url_for('user.register') }}"  class="menu-link">
            <i class="menu-icon tf-icons bx bx-user-plus" style="font-size: 26px;"></i>
            <div data-i18n="Register">Register</div>
        </a>
    </li>

    <li class="menu-item">
        <a href="/Forgot-Password"  class="menu-link">
            <i class="menu-icon tf-icons bx bx-home"></i>
            <div data-i18n="Forgot Password ?">Forgot Password ? </div>
        </a>
    </li>
</ul>

app/templates/user/_inc/menu.html
<ul class="menu-inner py-1 ps ps--active-y">
  <li class="menu-item">
      <a href="/"  class="menu-link">
        <i class="menu-icon tf-icons bx bx-home"></i>
        <div data-i18n="Home">Home</div>
      </a>
    </li>
    
    <li class="menu-item">
      <a href="{{ url_for('user.settings') }}"  class="menu-link">
        <i class="menu-icon tf-icons bx bx-cog"></i>
        <div data-i18n="Account Setting">Account Setting</div>
      </a>
    </li>
    
    <li class="menu-item">
      <a href="{{ url_for('user.logout') }}"  class="menu-link">
        <i class="menu-icon tf-icons bx bx-exit"></i>
        <div data-i18n="Logout">Logout</div>
      </a>
    </li>
</ul>