app/mod_application/group/models.py
"""
There is no model for the database. This item is stored in the user's own record as a pickle

"""

app/mod_application/group/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Length
from wtforms.fields import StringField, TextAreaField, SelectField

from utlis.forms import _get_fields
from utlis.dictionary import COLORs as COLORS

COLORs = COLORS()
class GroupForm(FlaskForm):
    title = StringField(description='Add Title',
                        validators=(DataRequired(), Length(1, 128)))
    
    description = TextAreaField(description='Add Description',
                                validators=(Length(0, 128),))
    
    color = SelectField(
        label='Select Group Color',
        choices=[
            (key, name)
            for key, name in COLORS.colors_bootstrap.items()
        ]
    )

    
    def get_fields(self):
        return _get_fields(self)
# End

app/mod_application/group/__init__.py
from flask import Blueprint

group = Blueprint('group', __name__, url_prefix='/group/')

from .routes import *

from utlis.flask_login import login_required

@group.before_request
@login_required('group.manage')
def login_required_group()->None:
    pass

app/mod_application/group/routes.py
# Flask libs
from flask import render_template, request, abort, flash, redirect, url_for, jsonify
from flask_login import current_user
from sqlalchemy.exc import IntegrityError
# - Flask libs

# Local libs
from . import group as buleprint_group
from .forms import GroupForm
from ..memory_management.group import GroupManager
from ..memory_management.event import EventManager
from ..memory_management.task import TasksManager

from utlis.dictionary import COLORs as COLORS
from app import db
# - Local libs

COLORs = COLORS()

@buleprint_group.route('/', methods=['GET'])
def manage():
    group_manager = GroupManager(
        pickle_data=current_user.groups)
    form = GroupForm()

    return render_template('application/group.html',
        title='Groups', form=form,
        groups=group_manager.list_groups,
        colors_dict=COLORs.colors_bootstrap)


@buleprint_group.route('/add', methods=['GET', 'POST'])
def add():
    form = GroupForm()
    
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash('Invalid forum', category='error')
            return redirect(url_for('group.manage'))
        # ----

        group_manager = GroupManager(
            pickle_data=current_user.groups)
        

        group_manager.add_group(
            title=form.title.data,
            color=form.color.data,
            description=form.description.data)
        
        # Save data in the database with (pickled) format
        current_user.groups = group_manager.return_group_in_pickle

        try:
            db.session.commit()

        except IndentationError:
            db.session.rollback()
            flash('Something went wrong, please try again', category='error')
        
        else:
            flash('New group successfully created', category='success')
            redirect(url_for('group.manage'))
    # ----
    return redirect(url_for('group.manage'))
# End Function

@buleprint_group.route('/edit/<string:title>', methods=['GET', 'POST'])
def edit(title:str):
    form = GroupForm()
    user:db_user = current_user
    
    event_manager = EventManager(
        pickle_data=user.events[0].events)
    
    task_manager = TasksManager(
        pickle_data=current_user.tasks[0].tasks)
    
    group_manager = GroupManager(
        pickle_data=current_user.groups)
    
    _selected_group = group_manager.groups.get(str(title))

    # Group Not Found
    if not _selected_group :
        return abort(404)
    # ----

    if request.method == 'GET':
        form.title.data = _selected_group.title
        form.description.data = _selected_group.description
        form.color.data = _selected_group.color
    # ----

    if request.method == 'POST':
        if not form.validate_on_submit():
            flash('Invalid forum', category='error')
            return render_template('application/form-edit-group.html', 
            title='Edit Group', form=form)
        # ----

        group_manager.update_group(
            target_title=title,
            title=form.title.data,
            color=form.color.data,
            description=form.description.data)

        # Edit events with this group
        for event in event_manager.list_events:
            if event.group_title == title:
                event.group_title = form.title.data

        # Edit task with this group
        for task in task_manager.list_tasks:
            if task.group_title == title:
                task.group_title = form.title.data
        
        # Save data in the database with (pickled) format
        current_user.groups = group_manager.return_group_in_pickle
        
        current_user.tasks[0].tasks = \
            task_manager.return_tasks_in_pickle
        
        current_user.events[0].events = \
            event_manager.return_events_in_pickle
        
        try:
            db.session.commit()
            
        except IndentationError:
            db.session.rollback()
            flash('Something went wrong, please try again', category='error')

        else:
            flash('Group edited successfully', category='success')
            return redirect(url_for('group.manage'))
    # ----
    return render_template('application/form-edit-group.html', 
                            title='Edit Group', form=form)
# End Function

@buleprint_group.route('/remove/<string:title>', methods=['GET'])
def remove(title:str):
    user:db_user = current_user
    
    event_manager = EventManager(
        pickle_data=user.events[0].events)
    
    task_manager = TasksManager(
        pickle_data=current_user.tasks[0].tasks)
    
    group_manager = GroupManager(
        pickle_data=current_user.groups)
    
    # Group Not Found
    if not group_manager.groups.get(str(title)):
        flash('Not Found Group, 404!', category='error')
        return redirect(url_for('group.manage'))
    # ----
    
    # Delete events with this group
    for event in event_manager.list_events:
        if event.group_title == title:
            event_manager.delete_event(int(event.id))
    # ---

    # Delete task with this group
    for task in task_manager.list_tasks:
        if task.group_title == title:
            task_manager.delete_task(int(task.id))
    # ---

    # Delete Group
    group_manager.delete_group(str(title))
    # ---

    # Save data in the database with (pickled) format
    current_user.groups = \
        group_manager.return_group_in_pickle

    current_user.tasks[0].tasks = \
        task_manager.return_tasks_in_pickle
    
    current_user.events[0].events = \
        event_manager.return_events_in_pickle
    # --- (End Seve)
    
    try:
        db.session.commit()
            
    except IndentationError:
        db.session.rollback()
        flash('Something went wrong, please try again', category='error')
    
    else:
        flash('Group delete successfully', category='success')
    
    return redirect(url_for('group.manage'))
# End Function

@buleprint_group.route('/json/get', methods=['GET'])
def send_json():
    group_manager = GroupManager(
        pickle_data=current_user.groups)
    
    data = {
        group.title : group.color
        for group in group_manager.groups.values()
        }
    
    return jsonify(data)

app/templates/application/base.html
{% extends "base.html" %}

{% block menu %}
    {% include '_inc/menu.html'   %}
{% endblock menu %}

app/templates/application/calendar.html
{% extends "application/base.html" %}


{% block page_js %}
<!-- Vendors JS -->
<script src="/static/assets/vendor/libs/fullcalendar/fullcalendar.js"></script>
<script src="/static/assets/vendor/libs/formvalidation/dist/js/FormValidation.min.js"></script>
<script src="/static/assets/vendor/libs/formvalidation/dist/js/plugins/Bootstrap5.min.js"></script>
<script src="/static/assets/vendor/libs/formvalidation/dist/js/plugins/AutoFocus.min.js"></script>
<script src="/static/assets/vendor/libs/select2/select2.js"></script>
<script src="/static/assets/vendor/libs/flatpickr/flatpickr.js"></script>
<script src="/static/assets/vendor/libs/moment/moment.js"></script>
<!-- Page JS -->
<script src="/static/assets/js/app-calendar-events.js"></script>
<script src="/static/assets/js/app-calendar.js"></script>
{% endblock page_js %}


{% block page_css %}
<!-- Vendors CSS -->
<link rel="stylesheet" href="/static/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
<link rel="stylesheet" href="/static/assets/vendor/libs/typeahead-js/typeahead.css" />
<link rel="stylesheet" href="/static/assets/vendor/libs/fullcalendar/fullcalendar.css" />
<link rel="stylesheet" href="/static/assets/vendor/libs/flatpickr/flatpickr.css" />
<link rel="stylesheet" href="/static/assets/vendor/libs/select2/select2.css" />
<link rel="stylesheet" href="/static/assets/vendor/libs/quill/editor.css" />
<link rel="stylesheet" href="/static/assets/vendor/libs/formvalidation/dist/css/formValidation.min.css" />
<!-- Page CSS -->
<link rel="stylesheet" href="/static/assets/vendor/css/pages/app-calendar.css" />
{% endblock page_css %}


{% block content %}
<!-- Group|Lable Data -->
<samp id='groupDataTag' 
      url_get="{{url_for('group.send_json')}}" 
      data='{ "Personal": "danger" }' 
      hidden></samp>

<!-- 
  I know this method is very stupid,
   but I didn't have enough time to make it!
   I will definitely fix it 
-->
<script>
let dataTag = document.getElementById('groupDataTag');
xhr = new XMLHttpRequest();
xhr.open("GET", dataTag.getAttribute('url_get'), true);
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.onload = function () {
    dataTag.setAttribute('data', this.responseText)};
xhr.send()
</script>
<!-- /Group|Lable Data -->


<div class="card app-calendar-wrapper">
  <div class="row g-0">
    <!-- Calendar Sidebar -->
    <div class="col app-calendar-sidebar" id="app-calendar-sidebar">
      <div class="border-bottom p-4 my-sm-0 mb-3">
        <div class="d-grid">
          <button class="btn btn-primary btn-toggle-sidebar" data-bs-toggle="offcanvas"
            data-bs-target="#addEventSidebar" aria-controls="addEventSidebar">
            <i class="bx bx-plus"></i>
            <span class="align-middle">Add Event</span>
          </button>
        </div>
      </div>
      <div class="p-4">
        <!-- inline calendar (flatpicker) -->
        <div class="ms-n2">
          <div class="inline-calendar"></div>
        </div>

        <hr class="container-m-nx my-4">

        <!-- Filter -->
        <div class="mb-4">
          <small class="text-small text-muted text-uppercase align-middle">Filter</small>
        </div>

        <div class="form-check mb-2">
          <input class="form-check-input select-all" type="checkbox" id="selectAll" data-value="all" checked>
          <label class="form-check-label" for="selectAll">View All</label>
        </div>

        <div class="app-calendar-events-filter">
          {% for title, color in _groups %}
            <div class="form-check form-check-{{color}} mb-2">
              <input class="form-check-input input-filter" type="checkbox" id="select-{{title.lower()}}" data-value="{{title.lower()}}"
                checked>
              <label class="form-check-label" for="select-{{title.lower()}}">{{title}}</label>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!-- /Calendar Sidebar -->

    <!-- Calendar & Modal -->
    <div class="col app-calendar-content">
      <div class="card shadow-none border-0">
        <div class="card-body pb-0">
          <!-- FullCalendar -->
          <div id="calendar"></div>
        </div>
      </div>
      <div class="app-overlay"></div>
      <!-- FullCalendar Offcanvas -->
      <div class="offcanvas offcanvas-end event-sidebar" tabindex="-1" id="addEventSidebar"
        aria-labelledby="addEventSidebarLabel">
        <div class="offcanvas-header border-bottom">
          <h5 class="offcanvas-title mb-2" id="addEventSidebarLabel">Add Event</h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <form action="{{ url_for('event.add') }}" class="event-form pt-0" id="eventForm" onsubmit="return false">
            <div class="mb-3">
              <label class="form-label" for="eventTitle">Title</label>
              <input type="text" class="form-control" id="eventTitle" name="eventTitle" placeholder="Event Title" />
            </div>
            <div class="mb-3">
              <label class="form-label" for="eventLabel">Label</label>
              <select class="select2 select-event-label form-select" id="eventLabel" name="eventLabel">

                {% for title, color in _groups %}
                <option data-label="{{color}}" value="{{title}}">{{title}}</option>  
                {% endfor %}
                
              </select>
            </div>
            <div class="mb-3">
              <label class="form-label" for="eventStartDate">Start Date</label>
              <input type="text" class="form-control" id="eventStartDate" name="eventStartDate"
                placeholder="Start Date" />
            </div>
            <div class="mb-3">
              <label class="form-label" for="eventEndDate">End Date</label>
              <input type="text" class="form-control" id="eventEndDate" name="eventEndDate" placeholder="End Date" />
            </div>
            <div class="mb-3">
              <label class="switch">
                <input type="checkbox" class="switch-input allDay-switch" disabled/>
                <span class="switch-toggle-slider">
                  <span class="switch-on"></span>
                  <span class="switch-off"></span>
                </span>
                <span class="switch-label">All Day</span>
              </label>
            </div>
            <div class="mb-3">
              <label class="form-label" for="eventURL">Event URL</label>
              <input type="url" class="form-control" id="eventURL" name="eventURL"
                placeholder="https://www.google.com" />
            </div>
            <div class="mb-3 select2-primary">
              <label class="form-label" for="eventReminder">Reminder</label>
              <select class="select2 select-event-guests form-select" 
                id="eventReminder" name="eventReminder" multiple>
                <option value="5">Minutes 5</option>
                <option value="10">Minutes 10</option>
                <option value="15">Minutes 15</option>
                <option value="30">Minutes 30</option>
                <option value="45">Minutes 45</option>
                <option value="60">Hour 1</option>
                <option value="90">Hour 1.5</option>
                <option value="120">Hour 2</option>
                <option value="180">Hour 3</option>
                <option value="240">Hour 4</option>
                <option value="300">Hour 5</option>
              </select>
              <span><small>
                For Multiple Seletct [Cltr + Click]
              </small></span>
            </div>
            <!-- <div class="mb-3">
              <label class="form-label" for="eventLocation">Location</label>
              <input type="text" class="form-control" id="eventLocation" name="eventLocation"
                placeholder="Enter Location" />
            </div> -->
            <div class="mb-3">
              <label class="form-label" for="eventDescription">Description</label>
              <textarea class="form-control" name="eventDescription" id="eventDescription"></textarea>
            </div>
            <div class="mb-3 d-flex justify-content-sm-between justify-content-start my-4">
              <div>
                <button type="submit" class="btn btn-primary btn-add-event me-sm-3 me-1">Add</button>
                <button type="reset" class="btn btn-label-secondary btn-cancel me-sm-0 me-1"
                  data-bs-dismiss="offcanvas">Cancel</button>
              </div>
              <div>
                <a class="btn btn-label-danger btn-delete-event d-none">Delete</a>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
    <!-- /Calendar & Modal -->
  </div>
</div>

<script>
  function asfsaf(){
    console.log('submit')
  }
  let formev = document.getElementById('eventForm');
  formev.addEventListener('submit', asfsaf);
</script>
{% endblock content %}

app/templates/application/form-edit-group.html
{% extends "application/base.html" %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="offcanvas-body mx-0 flex-grow-0" style="padding: 10px;">
            <form action="{{ request.full_path }}" method="post"
                class="add-new-user pt-0 fv-plugins-bootstrap5 fv-plugins-framework">

                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.title.label(class='form-label') }}
                    {{ form.title(class='form-control') }}
                </div>


                <div class="mb-3">
                    <div class="position-relative">
                        {{ form.color.label(class='form-label') }}
                        {{ form.color(class='select2 form-select select2-hidden-accessible') }}
                    </div>
                </div>

                <div class="mb-3">
                    {{ form.description.label(class='form-label') }}
                    {{ form.description(class='form-control') }}
                </div>


                <button type="submit" class="btn btn-primary me-sm-3 me-1 data-submit">
                    Submit
                </button>
                <button type="reset" class="btn btn-label-secondary" data-bs-dismiss="offcanvas">
                    Cancel
                </button>
                <input type="hidden">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/application/form-edit-task.html
{% extends "application/base.html" %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="offcanvas-body mx-0 flex-grow-0" style="padding: 10px;">
            <form action="{{ request.full_path }}" method="post"
                class="add-new-user pt-0 fv-plugins-bootstrap5 fv-plugins-framework">

                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.title.label(class='form-label') }}
                    {{ form.title(class='form-control') }}
                </div>



                <div class="mb-3">
                    {{ form.deadline.label(class='form-label') }}
                    {{ form.deadline(class='form-control') }}
                </div>

                <div class="mb-3">
                    <div class="position-relative">
                        {{ form.group.label(class='form-label') }}
                        {{ form.group(class='select2 form-select select2-hidden-accessible') }}
                    </div>
                </div>

                <div class="mb-3">
                    {{ form.description.label(class='form-label') }}
                    {{ form.description(class='form-control') }}
                </div>


                <button type="submit" class="btn btn-primary me-sm-3 me-1 data-submit">
                    Submit
                </button>
                <button type="reset" class="btn btn-label-secondary" data-bs-dismiss="offcanvas">
                    Cancel
                </button>
                <input type="hidden">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/application/group.html
{% extends "application/base.html" %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">

  <!-- Group Table -->
  <div class="card">
    <div class="card-header border-bottom">
      <h5 class="card-title">{{ title }}</h5>

      <div class="col-md-4 user_status">
        <button class="dt-button add-new btn btn-primary" style="width: 100%;" tabindex="0"
          aria-controls="DataTables_Table_0" type="button" data-bs-toggle="offcanvas"
          data-bs-target="#offcanvasAddUser">

          <span>
            <i class="bx bx-plus me-0 me-sm-1"></i>
            <span class="d-none d-sm-inline-block">
              Add New User
            </span>
          </span>

        </button>
      </div>

    </div>
  </div>

  <!-- Table Groups -->
  <div class="card-datatable table-responsive">
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">


      <!-- Table -->
      <table class="datatables-users table border-top dataTable no-footer dtr-column" id="DataTables_Table_0"
        aria-describedby="DataTables_Table_0_info">
        <thead>
          <tr>

            <th class="sorting sorting_desc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
              style="width: 101.516px;" aria-sort="descending" aria-label="User: activate to sort column ascending">

              Title
            </th>

            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
              style="width: 101.781px;" aria-label="Plan: activate to sort column ascending">

              Color
            </th>

            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
              style="width: 101.781px;" aria-label="Plan: activate to sort column ascending">

              Description
            </th>

            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 136.891px;" aria-label="Actions">

              Actions
            </th>

          </tr>
        </thead>
        <tbody>
          {% for group in groups %}
          <tr class="odd" title="Description : {{group.description}}">
            <td class="  control" tabindex="0" style="display: none;"></td>

            <td>
              <span class="text-truncate d-flex align-items-center">
                {{group.title}}
              </span>
            </td>

            <td>
              <span class="badge bg-{{group.color}}">
                {{colors_dict.get(group.color)}}
              </span>
            </td>

            <td>
              <span class="fw-medium">
                {{group.description[:26]}}...
              </span>
            </td>

            <td>
              <div class="d-inline-block text-nowrap">


                <a href="{{url_for('group.edit', title=group.title)}}">
                  <button class="btn btn-sm btn-icon">
                    <i class="bx bx-edit"></i>
                  </button>
                </a>

                <a href="{{url_for('group.remove', title=group.title)}}">
                  <button class="btn btn-sm btn-icon delete-record">
                    <i class="bx bx-trash"></i>
                  </button>
                </a>

              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <!-- /Table -->





      <div class="row mx-2">
        <div class="col-sm-12 col-md-6">
          <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">
            Showing {{groups|length}}</div>
        </div>
        <div class="col-sm-12 col-md-6">
          <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
            <ul class="pagination">
              <li class="paginate_button page-item previous disabled" id="DataTables_Table_0_previous"><a href="#"
                  aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>
              <li class="paginate_button page-item next disabled" id="DataTables_Table_0_next"><a href="#"
                  aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0" class="page-link">Next</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>



  <!-- Offcanvas to add new user -->
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasAddUser" aria-labelledby="offcanvasAddUserLabel">
    <div class="offcanvas-header">
      <h5 id="offcanvasAddUserLabel" class="offcanvas-title">
        Add Group
      </h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body mx-0 flex-grow-0">
      <form action="{{ url_for('group.add') }}" method="post"
        class="add-new-user pt-0 fv-plugins-bootstrap5 fv-plugins-framework">

        {{ form.hidden_tag() }}
        <div class="mb-3">
          {{ form.title.label(class='form-label') }}
          {{ form.title(class='form-control') }}
        </div>


        <div class="mb-3">
          <div class="position-relative">
            {{ form.color.label(class='form-label') }}
            {{ form.color(class='select2 form-select select2-hidden-accessible') }}
          </div>
        </div>

        <div class="mb-3">
          {{ form.description.label(class='form-label') }}
          {{ form.description(class='form-control') }}
        </div>


        <button type="submit" class="btn btn-primary me-sm-3 me-1 data-submit">
          Submit
        </button>
        <button type="reset" class="btn btn-label-secondary" data-bs-dismiss="offcanvas">
          Cancel
        </button>
        <input type="hidden">
      </form>
    </div>
  </div>
</div>
</div>

{% endblock content %}

app/templates/application/home.html
{% extends 'application/base.html' %}

{% block content %}
<div class="row mb-5">
    <a class="col-md" href="{{ url_for('event.manage') }}">
    <div class="col-md">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <img class="card-img card-img-left" src="/static/assets/img/icons/event.jpg" alt="Card image">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title h4">Calendar</h5>
              <p class="card-text" style="color: black;font-size:15px;">
                Software to manage and use your precious time optimally!
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    </a>
    <a class="col-md" href="{{ url_for('task.manage') }}">
    <div class="col-md">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title h4">To Do</h5>
              <p class="card-text" style="color: black;font-size:15px;">
                Software to manage and not forget your work !
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <img class="card-img card-img-right" src="/static/assets/img/icons/todo.jpg" alt="Card image">
          </div>
        </div>
      </div>
    </div>
    </a>
  </div>
{% endblock %}